export const learningPathResponse = {
  title: '4-Month Weekend Solidity Developer Learning Plan',
  start_date: '2026-09-10',
  end_date: '2027-01-09',
  learning_frequency: 'weekends',
  estimated_total_hours: 70,
  chapters: [
    {
      topic: 'Introduction to Blockchain, Ethereum and Web3',
      estimated_learning_time_in_hours: 8,
      planned_start_date: '2026-09-12',
      planned_end_date: '2026-09-20',
      description: 'Learn blockchain fundamentals, distributed ledgers, cryptographic hashing, wallets, accounts, transactions, blocks, consensus, Ethereum, Ether, smart contracts, dApps and the Ethereum development stack. The objective is to build the mental model needed before writing Solidity.',
      study_materials: [
        { title: 'Technical Introduction to Ethereum', link: 'https://ethereum.org/developers/docs/intro-to-ethereum/', type: 'reference' },
        { title: 'Ethereum Development Documentation', link: 'https://ethereum.org/developers/docs/', type: 'reference' },
        { title: 'Ethereum Whitepaper', link: 'https://ethereum.org/whitepaper/', type: 'pdf' },
        { title: 'Learn Solidity Smart Contract Development - Full Course', link: 'https://www.youtube.com/watch?v=-1GB6m39-rM', type: 'video' },
        { title: 'Mastering Ethereum', link: 'https://masteringethereum.xyz/', type: 'book' },
      ],
      quiz: [
        { question: 'What is the primary purpose of a blockchain?', options: ['To provide a shared tamper-resistant state or ledger', 'To replace all databases', 'To provide unlimited storage', 'To eliminate cryptography'], correct_option: 0 },
        { question: 'What is the native asset of Ethereum?', options: ['BTC', 'ETH', 'SOL', 'USDC'], correct_option: 1 },
        { question: 'What environment executes Ethereum smart-contract bytecode?', options: ['JVM', 'EVM', 'CLR', 'WASM'], correct_option: 1 },
        { question: 'Which term describes a record of transactions grouped into a block?', options: ['Ledger', 'Hash', 'Wallet', 'Nonce'], correct_option: 0 },
        { question: 'Which component allows users to sign transactions and control funds on Ethereum?', options: ['Wallet', 'Node', 'Compiler', 'Oracle'], correct_option: 0 },
        { question: 'What does decentralization reduce in a network?', options: ['Single points of failure', 'The need for public keys', 'The number of transactions', 'The size of blocks'], correct_option: 0 },
        { question: 'True or False: Ethereum smart contracts execute inside the Ethereum Virtual Machine.', options: ['True', 'False'], correct_option: 0 },
        { question: 'True or False: The native currency used to pay Ethereum transaction fees is ETH.', options: ['True', 'False'], correct_option: 0 },
      ],
    },
    {
      topic: 'Ethereum Accounts, Transactions, Gas and EVM',
      estimated_learning_time_in_hours: 8,
      planned_start_date: '2026-09-26',
      planned_end_date: '2026-10-04',
      description: 'Understand EOAs and contract accounts, transaction lifecycle, nonce, gas, calldata, return data, logs, events, contract creation and EVM execution. Learn enough EVM fundamentals to reason about what Solidity code actually does on-chain.',
      study_materials: [
        { title: 'Ethereum Accounts', link: 'https://ethereum.org/developers/docs/accounts/', type: 'reference' },
        { title: 'Ethereum Transactions', link: 'https://ethereum.org/developers/docs/transactions/', type: 'reference' },
        { title: 'Ethereum Virtual Machine', link: 'https://ethereum.org/developers/docs/evm/', type: 'reference' },
        { title: 'Ethereum Yellow Paper', link: 'https://ethereum.github.io/yellowpaper/paper.pdf', type: 'pdf' },
      ],
      quiz: [
        { question: 'Which account type is controlled by a private key?', options: ['Externally Owned Account', 'Contract Account', 'Validator Contract', 'Storage Account'], correct_option: 0 },
        { question: 'What does gas primarily measure?', options: ['Computational work required by an EVM operation', 'ETH account balance', 'Number of users', 'Block size in bytes'], correct_option: 0 },
        { question: 'Which EVM area keeps persistent state across transactions?', options: ['Storage', 'Memory', 'Stack', 'Calldata'], correct_option: 0 },
        { question: 'What is the purpose of a nonce in an Ethereum transaction?', options: ['To prevent replay attacks and track sender sequence', 'To store the sender balance', 'To increase block gas limit', 'To identify the block hash'], correct_option: 0 },
        { question: 'Which component receives transaction fees from execution?', options: ['Validator or block producer', 'Smart contract wallet', 'Oracle node', 'Compiler runtime'], correct_option: 0 },
        { question: 'What is the function of calldata?', options: ['It stores function arguments passed to a contract call', 'It stores persistent state', 'It holds the execution stack', 'It stores block headers'], correct_option: 0 },
        { question: 'True or False: Gas primarily measures the computational work required by an EVM operation.', options: ['True', 'False'], correct_option: 0 },
        { question: 'True or False: Persistent contract state is primarily stored in EVM storage.', options: ['True', 'False'], correct_option: 0 },
      ],
    },
    {
      topic: 'Solidity Fundamentals',
      estimated_learning_time_in_hours: 8,
      planned_start_date: '2026-10-10',
      planned_end_date: '2026-10-18',
      description: 'Learn Solidity syntax and core programming constructs: source files, pragma, contracts, variables, primitive types, arrays, mappings, structs, enums, functions, visibility, modifiers, constructors, events, errors, constants and immutables.',
      study_materials: [
        { title: 'Official Solidity Documentation', link: 'https://docs.solidity.org/en/latest/', type: 'reference' },
        { title: 'Solidity by Example', link: 'https://docs.solidity.org/en/latest/solidity-by-example.html', type: 'reference' },
        { title: 'Solidity Types', link: 'https://docs.solidity.org/en/latest/types.html', type: 'reference' },
        { title: 'Learn Solidity Smart Contract Development', link: 'https://updraft.cyfrin.io/courses/solidity', type: 'video' },
      ],
      quiz: [
        { question: 'Which keyword declares a Solidity contract?', options: ['contract', 'class', 'program', 'module'], correct_option: 0 },
        { question: 'Which keyword is used to define a contract function that does not change state?', options: ['view', 'constant', 'mutable', 'write'], correct_option: 0 },
        { question: 'What does a mapping in Solidity store?', options: ['Key-value pairs', 'A fixed-size array', 'A sequence of bytes', 'A named event'], correct_option: 0 },
        { question: 'Which data structure is best for representing a collection of related fields?', options: ['Struct', 'Mapping', 'Enum', 'Modifier'], correct_option: 0 },
        { question: 'Which of the following is a valid Solidity visibility specifier?', options: ['public', 'private', 'internal', 'all of the above'], correct_option: 3 },
        { question: 'What is the purpose of a constructor?', options: ['To initialize a contract at deployment', 'To emit events for every transaction', 'To define a new compiler version', 'To override storage layout'], correct_option: 0 },
        { question: 'True or False: The mapping keyword is used to define a key-value data structure in Solidity.', options: ['True', 'False'], correct_option: 0 },
        { question: 'True or False: A Solidity function that does not modify state can be declared with the view modifier.', options: ['True', 'False'], correct_option: 0 },
      ],
    },
    {
      topic: 'Advanced Solidity: Storage, Memory, Calldata, Ether and Contract Interaction',
      estimated_learning_time_in_hours: 8,
      planned_start_date: '2026-10-24',
      planned_end_date: '2026-11-01',
      description: 'Master Solidity data locations, storage layout, payable functions, Ether transfers, receive and fallback functions, msg.sender, msg.value, interfaces, contract-to-contract calls, call, delegatecall and staticcall.',
      study_materials: [
        { title: 'Solidity Contracts', link: 'https://docs.solidity.org/en/latest/contracts.html', type: 'reference' },
        { title: 'Solidity Types and Data Locations', link: 'https://docs.solidity.org/en/latest/types.html', type: 'reference' },
        { title: 'Solidity by Example', link: 'https://docs.solidity.org/en/latest/solidity-by-example.html', type: 'reference' },
      ],
      quiz: [
        { question: 'Which data location persists between transactions?', options: ['storage', 'memory', 'calldata', 'stack'], correct_option: 0 },
        { question: 'Which modifier allows a function to receive Ether?', options: ['payable', 'view', 'override', 'private'], correct_option: 0 },
        { question: 'What does msg.value represent?', options: ['The amount of Ether sent with the current call', 'The contract balance', 'The gas limit', 'The block timestamp'], correct_option: 0 },
        { question: 'Which type of variable stores temporary, mutable data during execution?', options: ['memory', 'storage', 'calldata', 'constant'], correct_option: 0 },
        { question: 'Which function can process incoming Ether without a specific function name?', options: ['receive()', 'fallback()', 'constructor()', 'transfer()'], correct_option: 0 },
        { question: 'Which function is used for low-level contract-to-contract call execution?', options: ['call()', 'send()', 'emit()', 'require()'], correct_option: 0 },
        { question: 'True or False: The payable modifier allows a function to receive Ether.', options: ['True', 'False'], correct_option: 0 },
        { question: 'True or False: msg.value represents the Wei sent with the current call.', options: ['True', 'False'], correct_option: 0 },
      ],
    },
    {
      topic: 'OpenZeppelin, Inheritance, Interfaces and Token Standards',
      estimated_learning_time_in_hours: 8,
      planned_start_date: '2026-11-07',
      planned_end_date: '2026-11-15',
      description: 'Learn inheritance, interfaces, libraries and reusable contracts, then use OpenZeppelin to implement production-style ERC-20, ERC-721 and ERC-1155 contracts. Understand ownership, role-based access control, allowances, minting, burning and token metadata.',
      study_materials: [
        { title: 'OpenZeppelin Contracts Documentation', link: 'https://docs.openzeppelin.com/contracts', type: 'reference' },
        { title: 'Ethereum Token Standards', link: 'https://ethereum.org/developers/docs/standards/tokens/', type: 'reference' },
        { title: 'OpenZeppelin Access Control', link: 'https://docs.openzeppelin.com/contracts/api/access', type: 'reference' },
      ],
      quiz: [
        { question: 'Which standard is commonly used for fungible Ethereum tokens?', options: ['ERC-20', 'ERC-721', 'ERC-1155', 'ERC-998'], correct_option: 0 },
        { question: 'Which standard is commonly used for NFTs?', options: ['ERC-721', 'ERC-20', 'ERC-777', 'ERC-4626'], correct_option: 0 },
        { question: 'What is the purpose of OpenZeppelin?', options: ['To provide reusable, audited smart contract components', 'To replace the EVM', 'To host chain data', 'To mine blocks'], correct_option: 0 },
        { question: 'Which role-based contract is commonly used for ownership control?', options: ['Ownable', 'EnumerableSet', 'ERC165', 'SafeMath'], correct_option: 0 },
        { question: 'What does an ERC-1155 token standard allow?', options: ['A single contract to manage multiple token types', 'Only one NFT and no fungible tokens', 'Only Ethereum block metadata', 'Only access control logic'], correct_option: 0 },
        { question: 'Which concept is used to restrict function calls to specific addresses?', options: ['Access control', 'Storage layout', 'Unit tests', 'Hashing'], correct_option: 0 },
        { question: 'True or False: ERC-721 is commonly used for NFTs.', options: ['True', 'False'], correct_option: 0 },
        { question: 'True or False: Ownable is a common OpenZeppelin component for simple single-owner authorization.', options: ['True', 'False'], correct_option: 0 },
      ],
    },
    {
      topic: 'Foundry Development, Testing and Deployment',
      estimated_learning_time_in_hours: 8,
      planned_start_date: '2026-11-21',
      planned_end_date: '2026-11-29',
      description: 'Set up a professional Solidity development workflow using Foundry. Learn forge, anvil and cast; project structure; compilation; deployment scripts; unit tests; revert testing; mocking; fork testing; fuzz testing and contract verification.',
      study_materials: [
        { title: 'Foundry Book', link: 'https://getfoundry.sh/', type: 'reference' },
        { title: 'Foundry Fundamentals', link: 'https://updraft.cyfrin.io/courses/foundry', type: 'video' },
        { title: 'Ethereum Smart Contract Testing', link: 'https://ethereum.org/developers/docs/smart-contracts/testing/', type: 'reference' },
      ],
      quiz: [
        { question: 'Which Foundry tool is primarily used for compiling, testing and deploying Solidity projects?', options: ['Forge', 'Anvil', 'Cast', 'Chisel'], correct_option: 0 },
        { question: 'Which Foundry tool provides a local Ethereum development node?', options: ['Anvil', 'Forge', 'Cast', 'Solc'], correct_option: 0 },
        { question: 'What is fuzz testing used for?', options: ['To test a contract against many generated inputs', 'To encrypt source code', 'To mine blocks', 'To deploy a blockchain'], correct_option: 0 },
        { question: 'Which artifact is typically used to deploy a contract in a Foundry project?', options: ['A script', 'A wallet', 'A hash', 'A VM image'], correct_option: 0 },
        { question: 'What does a verification step usually confirm?', options: ['That deployed bytecode matches the source code', 'That wallets are decentralized', 'That nodes are private keys', 'That gas is always zero'], correct_option: 0 },
        { question: 'Which command-line tool is used for interacting with contracts and sending transactions?', options: ['cast', 'forge', 'anvil', 'solc'], correct_option: 0 },
        { question: 'True or False: Foundry\'s local Ethereum node is called Anvil.', options: ['True', 'False'], correct_option: 0 },
        { question: 'True or False: Fuzz testing is intended to test a contract against many automatically generated input values.', options: ['True', 'False'], correct_option: 0 },
      ],
    },
    {
      topic: 'DeFi, Oracles, Composability and dApp Integration',
      estimated_learning_time_in_hours: 8,
      planned_start_date: '2026-12-05',
      planned_end_date: '2026-12-13',
      description: 'Understand decentralized finance architecture, smart-contract composability, price oracles, lending, swaps, liquidity pools, collateral and protocol integrations. Build a small DeFi-style project using Chainlink Data Feeds and learn how a TypeScript frontend can interact with Solidity contracts.',
      study_materials: [
        { title: 'Chainlink Developer Documentation', link: 'https://docs.chain.link/', type: 'reference' },
        { title: 'Smart Contract Composability', link: 'https://ethereum.org/developers/docs/smart-contracts/composability/', type: 'reference' },
        { title: 'Cyfrin FundMe Project', link: 'https://updraft.cyfrin.io/courses/foundry', type: 'video' },
      ],
      quiz: [
        { question: 'What is the primary purpose of a blockchain oracle?', options: ['Provide external data to smart contracts', 'Store private keys', 'Mine Bitcoin', 'Compile Solidity'], correct_option: 0 },
        { question: 'What does smart-contract composability allow?', options: ['Contracts to interact with and build on each other', 'Nodes to increase gas fees', 'Wallets to manage keys automatically', 'Block headers to be skipped'], correct_option: 0 },
        { question: 'Which concept best describes a protocol that lets users trade assets through liquidity pools?', options: ['Decentralized exchange', 'Centralized bank', 'Database index', 'Compiler cache'], correct_option: 0 },
        { question: 'Why do dApps rely on oracles?', options: ['To fetch off-chain data such as prices', 'To generate new transactions', 'To reduce blockchain size', 'To encrypt all state'], correct_option: 0 },
        { question: 'Which mechanism is often used to manage loan collateral in DeFi?', options: ['Collateralized borrowing', 'Proof of work', 'Peer-to-peer hashing', 'Key rotation'], correct_option: 0 },
        { question: 'What is a key benefit of composability in DeFi?', options: ['Protocols can combine features without rebuilding the stack', 'Only one application can use a protocol', 'Ethereum blocks become smaller', 'Every contract must be handwritten'], correct_option: 0 },
        { question: 'True or False: A service that supplies external information to smart contracts is called an oracle.', options: ['True', 'False'], correct_option: 0 },
        { question: 'True or False: DeFi is short for decentralized finance.', options: ['True', 'False'], correct_option: 0 },
      ],
    },
    {
      topic: 'Smart Contract Security, Gas Optimization and Advanced Solidity',
      estimated_learning_time_in_hours: 8,
      planned_start_date: '2026-12-19',
      planned_end_date: '2026-12-27',
      description: 'Develop a security-first mindset. Study reentrancy, access-control bugs, tx.origin, oracle manipulation, denial of service, unchecked arithmetic, unsafe external calls, signature replay, MEV/front-running, storage layout, gas optimization, custom errors, assembly fundamentals and upgradeability concepts.',
      study_materials: [
        { title: 'Solidity Security Considerations', link: 'https://docs.solidity.org/en/latest/security-considerations.html', type: 'reference' },
        { title: 'OpenZeppelin Contracts', link: 'https://docs.openzeppelin.com/contracts', type: 'reference' },
        { title: 'Ethereum Smart Contract Security Guidelines', link: 'https://ethereum.org/developers/tutorials/smart-contract-security-guidelines/', type: 'reference' },
      ],
      quiz: [
        { question: 'What is a reentrancy attack?', options: ['An external call causes control to return to a vulnerable contract before its state is safely updated', 'A contract is compiled twice', 'A user submits two unrelated transactions', 'A block contains multiple transactions'], correct_option: 0 },
        { question: 'Which pattern reduces reentrancy risk?', options: ['Checks-Effects-Interactions', 'Compile-Deploy-Verify', 'Hash-Order-Retrieve', 'Read-Write-Reset'], correct_option: 0 },
        { question: 'What is front-running?', options: ['Submitting or ordering a transaction strategically after observing another pending transaction', 'Adding a transaction to a wallet', 'Compiling a contract before deployment', 'Encrypting a block header'], correct_option: 0 },
        { question: 'Which of the following is a common gas optimization practice?', options: ['Fewer storage writes and efficient data packing', 'Storing everything in memory permanently', 'Avoiding function modifiers', 'Disabling events entirely'], correct_option: 0 },
        { question: 'Why is tx.origin considered risky?', options: ['It can be spoofed and misused for authorization', 'It stores gas prices', 'It is required for every function call', 'It always tracks the block height'], correct_option: 0 },
        { question: 'Which variable is commonly used to identify the immediate caller?', options: ['msg.sender', 'block.timestamp', 'tx.origin', 'keccak256'], correct_option: 0 },
        { question: 'True or False: Checks-Effects-Interactions helps reduce reentrancy risk.', options: ['True', 'False'], correct_option: 0 },
        { question: 'True or False: The Solidity global variable commonly preferred for identifying the immediate caller is msg.sender.', options: ['True', 'False'], correct_option: 0 },
      ],
    },
    {
      topic: 'Capstone Project, Deployment, Portfolio and Solidity Developer Interview Preparation',
      estimated_learning_time_in_hours: 14,
      planned_start_date: '2027-01-02',
      planned_end_date: '2027-01-09',
      description: 'Build a complete portfolio-grade Solidity project combining the skills from the previous chapters. Recommended project: a decentralized expert-services marketplace with ERC-20 payments, expert registration, role-based access control, escrow, commissions, reputation, dispute handling, events, comprehensive Foundry tests, fuzz/invariant testing, deployment scripts and contract verification. Finish by reviewing EVM, Solidity, security, testing and smart-contract system-design interview questions.',
      study_materials: [
        { title: 'Ethereum dApp Documentation', link: 'https://ethereum.org/developers/docs/dapps/', type: 'reference' },
        { title: 'Deploying Smart Contracts', link: 'https://ethereum.org/developers/docs/smart-contracts/deploying/', type: 'reference' },
        { title: 'Verifying Smart Contracts', link: 'https://ethereum.org/developers/docs/smart-contracts/verifying/', type: 'reference' },
        { title: 'Foundry Book', link: 'https://getfoundry.sh/', type: 'reference' },
      ],
      quiz: [
        { question: 'What should be the primary purpose of a Solidity portfolio project?', options: ['Demonstrate production-oriented smart-contract development skills', 'Contain as many lines of code as possible', 'Avoid automated testing', 'Use only tutorial code without modifications'], correct_option: 0 },
        { question: 'Which artifact documents the trust assumptions and attack paths of a protocol?', options: ['Threat model', 'Deployment script', 'Wallet seed phrase', 'Gas limit'], correct_option: 0 },
        { question: 'Which testing style is especially useful for large state-machine scenarios?', options: ['Invariant testing', 'Copy-paste testing', 'Static text checking', 'Browser screenshot tests'], correct_option: 0 },
        { question: 'What is the goal of a capstone project in this curriculum?', options: ['To integrate the full skill set into a realistic project', 'To avoid writing tests', 'To reduce learning time to zero', 'To eliminate user interfaces'], correct_option: 0 },
        { question: 'Which of the following is typically included in a strong protocol audit checklist?', options: ['Access control, reentrancy, arithmetic, and oracle assumptions', 'Wallet brand alignment, CSS styling, and favicon usage', 'Only code comments', 'Only deployment timing'], correct_option: 0 },
        { question: 'Which concept describes a condition that must always remain true during execution?', options: ['Invariant', 'Constructor', 'Fallback', 'Oracle'], correct_option: 0 },
        { question: 'True or False: A threat model best documents the security assumptions of a smart-contract system.', options: ['True', 'False'], correct_option: 0 },
        { question: 'True or False: Invariant testing is particularly useful for discovering unexpected state-machine bugs.', options: ['True', 'False'], correct_option: 0 },
      ],
    },
  ],
} as const
